// src/config/client.ts
export const CLIENT = {
  name: "ADRIANA MARTINS - CONSULTORA FINANCEIRA",
  logo: "https://f58ee20228d9ca2cf6ae548dbcf2204b.r2.cloudflarestorage.com/creative-post-storage/projects/prj_adriana-consultora/assets/logo-dark.png?X-Amz-Expires=3600&X-Amz-Date=20260430T182745Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=b934f0556c87eb9d9e2b56da7aeeed98%2F20260430%2Fauto%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=9694d940ef84e4e2143c411d4f5352080c41692367665bed2a66fc95af0b6f81",
  favicon: "/images/favicon.png",
  siteUrl: "https://lp-adriana-martins-consultora-financeira.pages.dev",
  seo: {
    title: "ADRIANA MARTINS - CONSULTORA FINANCEIRA - Lucro Previsível para Empresas",
    description: "Consultoria financeira especializada para empreendedores, focada em transformar o caos financeiro em lucro previsível em até 90 dias com a Mentoria ACTUL.",
  },
  og: { image: "/images/og.jpg" },
  schema: {
    type: "Physician",
    streetAddress: "",
    addressLocality: "",
    addressRegion: "",
    postalCode: "",
    sameAs: [] as string[],
  },
  fontsUrl: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap",
  fonts: {
    display: "Inter",
    body: "Inter",
  },
  gtmId: "GTM-XXXXXXX",
  webhookUrl: "https://webhooks02.manager01.growdoc.com.br/webhook/redirect-global",
  captureUrl: "https://lswmkiyqznvuedbuyrkt.supabase.co/functions/v1/capture-lead",
  location: "Online",
  hero: {
    eyebrow: "ADRIANA MARTINS - CONSULTORA FINANCEIRA",
    headingLines: ["Do caos ao lucro previsível em até 90 dias com a ","Mentoria ACTUL"],
    credentials: ["Para empreendedores com faturamento acima de R$ 30 mil/mês."],
    formTitle: "[ADRIANA GOMES] Formulário qualificatório LP",
    ctaText: "QUERO FAZER A APLICAÇÃO",
  },
  desires: {
    eyebrow: "QUER ORGANIZAR SUA EMPRESA E TER LUCRO PREVISÍVEL?",
    heading: "O primeiro passo começa aqui.",
    items: [{"num":"✅","text":"Organize suas finanças com clareza, sem achismos nem planilhas soltas."},{"num":"✅","text":"Aprenda a precificar corretamente seus serviços e produtos com margem real."},{"num":"✅","text":"Transforme o faturamento em lucro com base em dados e estratégia."},{"num":"✅","text":"Tire o dono do operacional e crie processos para crescer com segurança."},{"num":"✅","text":"Tenha um plano estruturado para tomar decisões com confiança."}],
    ctaSubtext: "A solução que você precisa para sair do caos financeiro e transformar seu negócio com um plano claro e sob controle.",
  },
  services: {
    eyebrow: "CONHEÇA O MÉTODO ACTUL",
    heading: "DO CAOS AO",
    headingEm: "LUCRO",
    items: [{"num":"1","title":"ANÁLISE FINANCEIRA","description":"Raio-X do seu negócio, identificação dos vazamentos e plano imediato de ação."},{"num":"2","title":"ANÁLISE FINANCEIRA","description":"Construção da DRE, ponto de equilíbrio e meta de lucro com clareza."},{"num":"3","title":"CRIAÇÃO DE FERRAMENTAS","description":"Precificação com margem, mapa de rentabilidade e reajuste estratégico."},{"num":"4","title":"TOMADA DE DECISÃO COM DADOS","description":"Projeção realista, retirada consciente e rotina semanal de controle."},{"num":"5","title":"UNIFICAÇÃO DA GESTÃO","description":"Integração entre financeiro, operação e equipe com indicadores e plano de ação."},{"num":"6","title":"LUCRO SUSTENTÁVEL","description":"Metas para os próximos 90 dias e plano de crescimento com estrutura."}],
  },
  testimonials: [{"title":"\"UM DIVISOR DE ÁGUAS NA MINHA VIDA EMPRESARIAL\"","body":"“Foi maravilhoso... aprendi muito e agora me sinto preparada pra administrar e crescer a minha empresa. Só façam!”","author":"Carina Lemos"},{"title":"\"MUDANÇA QUE VAI TRANSFORMAR MINHA EMPRESA\"","body":"“Sem palavras para agradecer a mudança que vai fazer na minha vida e na minha empresa. Sou muito grata por essa oportunidade 🙏 Adriana, você é d+”","author":"Camila Tavares"},{"title":"\"UMA VIRADA DE CHAVE NUM PISCAR DE OLHOS\"","body":"“Foi incrível. Grandioso esse conhecimento. Tive a certeza que estava trabalhando errado. Mas graças a Deus, foi tudo perfeito. Excelente profissional.”","author":"Nathália Carolina"},{"title":"\"EXCELENTE PROFISSIONAL, COM VISÃO COMPLETA DA EMPRESA\"","body":"“Recomendo bastante. Boa em Gestão Completa Empresarial e realmente procura entender a necessidade da empresa!”","author":"Giovanni Molinari"},{"title":"\"EU ESTAVA FAZENDO TUDO ERRADO — E NEM SABIA\"","body":"“Aprendi muita coisa. Percebi que estava fazendo tudo errado. Obrigada, Adriana, pelo ensinamento.”","author":"Giceli L. Jação"}],
  process: {
    eyebrow: "Como Funciona",
    heading: "Do primeiro contato ao",
    headingEm: "resultado",
    steps: [
      { num: "01", title: "AGENDAMENTO", description: "Entre em contato e agende sua consulta." },
      { num: "02", title: "CONSULTA", description: "Avaliação detalhada e planejamento do tratamento." },
      { num: "03", title: "PROCEDIMENTO", description: "Realização com técnica e segurança." },
      { num: "04", title: "RESULTADO", description: "Acompanhamento e resultado esperado." },
    ],
  },
  beforeAfter: {
    eyebrow: "Resultados Reais",
    heading: "Transformações que",
    headingEm: "falam por si",
    disclaimer: "Resultados podem variar. Imagens de pacientes que autorizaram o uso.",
    items: [] as { label: string; beforeSrc: string; afterSrc: string }[],
  },
  faq: {
    eyebrow: "Dúvidas Frequentes",
    heading: "Perguntas que os pacientes mais fazem",
    items: [] as { question: string; answer: string }[],
  },
  mapSection: {
    eyebrow: "Localização",
    heading: "Venha nos conhecer",
    address: "",
    complement: "",
    schedule: "Atendimento online com agendamento prévio.",
    phone: "",
    mapsUrl: "https://maps.google.com",
    mapsEmbed: "https://www.google.com/maps/embed?pb=",
  },
  locationSection: {
    eyebrow: "Nossa Estrutura",
    heading: "Conheça o ADRIANA MARTINS - CONSULTORA FINANCEIRA",
    locations: [{ city: "Online", name: "ADRIANA MARTINS - CONSULTORA FINANCEIRA", address: "Atendimento online", description: "Consultoria financeira especializada para empreendedores, totalmente online." }],
    stats: [] as { value: string; label: string }[],
  },
  gallery: {
    eyebrow: "Estrutura",
    heading: "Conheça o ADRIANA MARTINS - CONSULTORA FINANCEIRA",
    description: "",
    images: [] as { src: string; alt: string }[],
  },
  doctors: [
    {
      crm: "",
      name: "Adriana Martins",
      specialty: "Consultora Financeira",
      bio: ["Adriana Martins é uma consultora financeira experiente, especializada em ajudar empreendedores a organizar suas finanças e alcançar um lucro previsível. Com a Mentoria ACTUL, ela guia empresas com faturamento acima de R$ 30 mil/mês rumo à estabilidade e crescimento financeiro."],
      credentials: ["Para empreendedores com faturamento acima de R$ 30 mil/mês."],
      photo: "https://f58ee20228d9ca2cf6ae548dbcf2204b.r2.cloudflarestorage.com/creative-post-storage/projects/prj_adriana-consultora/assets/photo-professional.jpg?X-Amz-Expires=3600&X-Amz-Date=20260430T182745Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=b934f0556c87eb9d9e2b56da7aeeed98%2F20260430%2Fauto%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=572ccd040d827ba5be320ab6c147c4017b3552b61a32e66eff83947716f08438",
    },
  ],
  linksUteis: { items: [] as { label: string; href: string }[] },
  footer: {
    year: new Date().getFullYear(),
    copyright: "Adriana Martins - Consultora Financeira · Todos os direitos reservados",
  },
} as const